name: Build and publish python package

on:
  release:
    types: [ published ]

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'

      - name: Install Poetry and Poetry-core
        run: |
          pip install --upgrade pip
          pip install --upgrade poetry poetry-core

      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1
        with:
          BRANCH: main
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}

